# Chapter 7

# Prepare Your Data For Machine Learning

## Rescale Data

In [ ]:
# Import các thư viện cần thiết
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

# Đọc dữ liệu từ file CSV
filename = 'diabetes.csv'
data = read_csv(filename)

# Chuyển dữ liệu từ DataFrame sang mảng numpy
array = data.values # chuyển đổi thành mảng numpy
X = array[:,0:8] # lấy 8 cột đầu tiên làm dữ liệu đầu vào
Y = array[:,8] # lấy cột cuối cùng làm nhãn

# Khởi tạo bộ MinMaxScaler để chuẩn hóa dữ liệu về khoảng từ 0 đến 1
scaler = MinMaxScaler(feature_range=(0, 1)) # chuẩn hóa giá trị về khoảng từ 0 đến 1

# Áp dụng chuẩn hóa dữ liệu
resCaledX = scaler.fit_transform(X) # chuẩn hóa toàn bộ dữ liệu về khoảng từ 0 đến 1

# Thiết lập hiển thị số thập phân với 3 chữ số sau dấu phẩy
set_printoptions(precision=3) # in ra 3 chữ số sau dấu phẩy

# In ra 5 dòng đầu tiên của dữ liệu đã được chuẩn hóa
print(resCaledX[0:5,:]) # in ra 5 dòng đầu tiên

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


## Standardize Data

In [ ]:
# Import các thư viện cần thiết
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import StandardScaler

# Đọc dữ liệu từ file CSV
filename = 'diabetes.csv'
data = read_csv(filename)

# Chuyển dữ liệu từ DataFrame sang mảng numpy
array = data.values # chuyển đổi thành mảng numpy
X = array[:,0:8] # lấy 8 cột đầu tiên làm dữ liệu đầu vào
Y = array[:,8] # lấy cột cuối cùng làm nhãn

# Khởi tạo bộ StandardScaler để chuẩn hóa dữ liệu
scaler = StandardScaler().fit(X) # chuẩn hóa dữ liệu theo phân phối chuẩn

# Áp dụng chuẩn hóa dữ liệu
resCaledX = scaler.transform(X) # chuẩn hóa toàn bộ dữ liệu

# Thiết lập hiển thị số thập phân với 3 chữ số sau dấu phẩy
set_printoptions(precision=3) # in ra 3 chữ số sau dấu phẩy

# In ra 5 dòng đầu tiên của dữ liệu đã được chuẩn hóa
print(resCaledX[0:5,:]) # in ra 5 dòng đầu tiên

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


## Normalize Data

In [ ]:
# Import các thư viện cần thiết
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import Normalizer

# Đọc dữ liệu từ file CSV
filename = 'diabetes.csv'
data = read_csv(filename)

# Chuyển dữ liệu từ DataFrame sang mảng numpy
array = data.values # chuyển đổi thành mảng numpy
X = array[:,0:8] # lấy 8 cột đầu tiên làm dữ liệu đầu vào
Y = array[:,8] # lấy cột cuối cùng làm nhãn

# Khởi tạo bộ Normalizer để chuẩn hóa dữ liệu
scaler = Normalizer().fit(X) # chuẩn hóa dữ liệu về khoảng từ 0 đến 1

# Áp dụng chuẩn hóa dữ liệu
resCaledX = scaler.transform(X) # chuẩn hóa toàn bộ dữ liệu về khoảng từ 0 đến 1

# Thiết lập hiển thị số thập phân với 3 chữ số sau dấu phẩy
set_printoptions(precision=3) # in ra 3 chữ số sau dấu phẩy

# In ra 5 dòng đầu tiên của dữ liệu đã được chuẩn hóa
print(resCaledX[0:5,:]) # in ra 5 dòng đầu tiên

[[0.034 0.828 0.403 0.196 0.    0.188 0.004 0.28 ]
 [0.008 0.716 0.556 0.244 0.    0.224 0.003 0.261]
 [0.04  0.924 0.323 0.    0.    0.118 0.003 0.162]
 [0.007 0.588 0.436 0.152 0.622 0.186 0.001 0.139]
 [0.    0.596 0.174 0.152 0.731 0.188 0.01  0.144]]


## Binarize Data

In [ ]:
# Import các thư viện cần thiết
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import Binarizer

# Đọc dữ liệu từ file CSV
filename = 'diabetes.csv'
data = read_csv(filename)

# Chuyển dữ liệu từ DataFrame sang mảng numpy
array = data.values # chuyển đổi thành mảng numpy
X = array[:,0:8] # lấy 8 cột đầu tiên làm dữ liệu đầu vào
Y = array[:,8] # lấy cột cuối cùng làm nhãn

# Khởi tạo bộ Binarizer để chuyển đổi dữ liệu thành giá trị 0 và 1
scaler = Binarizer(threshold=0.0).fit(X) # chuyển đổi giá trị thành 0 và 1 dựa trên ngưỡng

# Áp dụng chuẩn hóa dữ liệu
resCaledX = scaler.transform(X) # chuẩn hóa toàn bộ dữ liệu về 0 và 1

# Thiết lập hiển thị số thập phân với 3 chữ số sau dấu phẩy
set_printoptions(precision=3) # in ra 3 chữ số sau dấu phẩy

# In ra 5 dòng đầu tiên của dữ liệu đã được chuẩn hóa
print(resCaledX[0:5,:]) # in ra 5 dòng đầu tiên

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]
